exec-once=swaync -c ~/.config/mango/config/swaync/config.jsonc -s ~/.config/mango/config/swaync/style.css
exec-once=wlsunset -T 3501 -t 3500
exec-once=awww-daemon
exec-once=awww img ~/.config/mango/config/wallpaper/wallpaper.png
exec-once=waybar -c ~/.config/mango/config/waybar/config.jsonc -s ~/.config/mango/config/waybar/style.css
exec-once=echo "Xft.dpi: 140" | xrdb -merge
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0
exec=once=wl-paste --type text --watch cliphist store
exec-once=blueman-applet
exec-once=nm-applet
exec-once=/usr/lib/soteria-polkit/soteria
exec-once=sway-audio-idle-inhibit
exec-once=swayosd-server
exec-once=throne
exec-once=vesktop
exec-once=Telegram
