#keyboard layout
xkb_rules_layout=us,ru
xkb_rules_options = grp:alt_shift_toggle

#common keymode
keymode=common
bind=SUPER,w,setkeymode,default
bind=SUPER,e,setkeymode,special

#audio
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @default_audio_sink@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @default_audio_sink@ 5%-
bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @default_source@ toggle

#screenshot
bind=NONE,Print,spawn,env QT_ENABLE_HIGHDPI_SCALING=0 flameshot gui
bind=SUPER,Print,spawn, ~/.config/mango/scripts/flameshot.sh

#default keymode
keymode=default

#keys
bind=SUPER,Return,spawn,foot
bind=SUPER,d,spawn,fuzzel
bind=SUPER,m,quit
bind=SUPER,q,killclient
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,f,togglefakefullscreen
bind=SUPER,o,toggleoverview,0
bind=SUPER,s,toggle_scratchpad
bind=SUPER,a,minimized
bind=SUPER+SHIFT,a,restore_minimized
bind=SUPER,semicolon,spawn,swaylock -f -c 000000
bind=SUPER,u,viewtoleft,0
bind=SUPER,i,viewtoright,0
bind=SUPER,v,togglefloating
bind=SUPER,c,reload_config
bind=SUPER+SHIFT,c,~/.config/mango/scripts/reload.sh

#move window focus with hjkl
bind=SUPER,Left,focusdir,left
bind=SUPER,Down,focusdir,down
bind=SUPER,Up,focusdir,up
bind=ALT,Right,focusdir,right

#move window focus with arrows
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right

#move window with arrows
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

#move window with arrows
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Right,exchange_client,right

#view tags
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER,10,view,10,0

#move window to tag
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

#special keymode
keymode=special

bind=SUPER,t,setlayout,tile
bind=SUPER+SHIFT,t,setlayout,vertical_tile
bind=SUPER,c,setlayout,center_tile
bind=SUPER,r,setlayout,right_tile
bind=SUPER,s,setlayout,scroller
bind=SUPER+SHIFT,s,setlayout,vertical_scroller
bind=SUPER,m,setlayout,monocle
bind=SUPER,g,setlayout,grid
bind=SUPER+SHIFT,g,setlayout,vertical_grid
bind=SUPER,d,setlayout,deck
bind=SUPER+SHIFT,d,setlayout,vertical_deck
bind=SUPER,x,setlayout,tgmix

#resize window with hjkl
bind=SUPER,h,resizewin,-50,+0
bind=SUPER,j,resizewin,+0,+50
bind=SUPER,k,resizewin,+0,-50
bind=SUPER,l,resizewin,+50,+0

#resize window with arrows
bind=SUPER,Left,resizewin,-50,+0
bind=SUPER,Down,resizewin,+0,+50
bind=SUPER,Up,resizewin,+0,-50
bind=SUPER,Right,resizewin,+50,+0

bind=SUPER+SHIFT,h,focusmon,left
bind=SUPER+SHIFT,j,focusmon,down
bind=SUPER+SHIFT,k,focusmon,up
bind=SUPER+SHIFT,l,focusmon,right
