#DEFAULT LAYOUT
#keys
bind=SUPER,Return
bind=SUPER,d,spawn,fuzzel
bind=SUPER,m,quit
bind=SUPER,q,killclient
bind=SUPER,c,reload_config
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,f,togglefakefullscreen
bind=SUPER,o,toggleoverview,0
bind=SUPER,s,toggle_scratchpad
bind=SUPER,a,minimized
bind=SUPER+SHIFT,a,bind=SUPER,i,minimized
bind=SUPER+SHIFT,l,spawn,swaylock -f -c 000000

bind=SUPER+SHIFT,c,reload_config.sh

#move window focus
bind=SUPER,Left,focusdir,left
bind=SUPER,Down,focusdir,down
bind=SUPER,Up,focusdir,up
bind=ALT,Right,focusdir,right

bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=ALT,l,focusdir,right


#tags
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER,10,view,10,0

#audio
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @default_audio_sink@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @default_audio_sink@ 5%-
bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @default_source@ toggle


#SECONDARY LAYOUT
#change layout
bind=SUPER,t,setlayout,tile
bind=SUPER+SHIFT,t,setlayout,vertical_tile
bind=SUPER,c,setlayout,center_tile
bind=SUPER,r,setlayout,right_tile
bind=SUPER,s,setlayout,scroller
bind=SUPER+SHIFT,s,vertical scroller
bind=SUPER,m,setlayout,monocle
bind=SUPER,g,setlayout,grid
bind=SUPER+SHIFT,g,setlayout,vertical grid
bind=SUPER,d,setlayout,deck
bind=SUPER+SHIFT,d,setlayout,vertical_deck
bind=SUPER,x,setlayout,tgmix

# resize window
bind=SUPER,h,resizewin,-50,+0
bind=SUPER,j,resizewin,+0,+50
bind=SUPER,k,resizewin,+0,-50
bind=SUPER,l,resizewin,+50,+0

bind=SUPER,Left,resizewin,-50,+0
bind=SUPER,Down,resizewin,+0,+50
bind=SUPER,Up,resizewin,+0,-50
bind=SUPER,Right,resizewin,+50,+0
