bind=SUPER,Left,focusdir,h
bind=SUPE,Right,focusdir,l
bind=SUPER,Up,focusdir,k
bind=SUPER,Down,focusdir,j
full screen win+f
fake full screen win+shift+f
bind=SUPER,Return,spawn,foot
bind=SUPER,d,spawn,fuzzel
bind=SUPER,q,killclient
bind=SUPER,m,quit
floating toggle win+shift+space
bind=SUPER,c,reload_config
bind=SUPER+SHIFT,c,reload_all.sh
