# Overview Setting
hotarea_size=10
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=alt,btn_middle,set_proportion,0.5
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+CTRL,btn_left,minimized
mousebind=SUPER+CTRL,btn_right,killclient
mousebind=SUPER+CTRL,btn_middle,togglefullscreen
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=NONE,btn_left,toggleoverview,1
mousebind=NONE,btn_right,killclient,0

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
axisbind=alt,UP,focusdir,left
axisbind=alt,DOWN,focusdir,right
axisbind=shift+super,UP,exchange_client,left
axisbind=shift+super,DOWN,exchange_client,right
