sloppyfocus=1
enable_hotarea=1

# Overview Setting
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# Mouse Button Bindings
mousebind=NONE,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,set_proportion,0.5
mousebind=NONE,btn_right,moveresize,curresize
mousebind=NONE,btn_left,minimized
mousebind=NONE,btn_right,killclient
mousebind=NONE,btn_middle,togglefullscreen
mousebind=NONE,btn_middle,togglemaximizescreen,0

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
axisbind=alt,UP,focusdir,left
axisbind=alt,DOWN,focusdir,right
axisbind=shift+super,UP,exchange_client,left
axisbind=shift+super,DOWN,exchange_client,right
