bind=,j,exec,wlrctl pointer move 0 10
bind=,k,exec,wlrctl pointer move 0 -10
bind=,l,exec,wlrctl pointer move 10 0
bind=,h,exec,wlrctl pointer move -10 0

# Left button
bind=,s,exec,wlrctl pointer click left
# Middle button
bind=,d,exec,wlrctl pointer click middle
# Right button
bind=,f,exec,wlrctl pointer click right

# Scroll up and down
bind=,e,exec,wlrctl pointer scroll 10 0
bind=,r,exec,wlrctl pointer scroll -10 0

# Scroll left and right
bind=,t,exec,wlrctl pointer scroll 0 -10
bind=,g,exec,wlrctl pointer scroll 0 10
